name: Update Servant Data JSON

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run update script
        uses: zejba/get-fgo-data@master
        with:
          servantDataJSONPath: output/servant_data.json

      - name: Commit and push changes
        run: |
          git config --local user.email "66516617+zejba@users.noreply.github.com"
          git config --local user.name "zejba"
          git add output/servant_data.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Servant Data JSON"
            git push
          fi
